index:
    path: /{_locale}
    controller: App\Controller\DefaultController::index
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr

contact:
    path: /{_locale}/contact
    controller: App\Controller\DefaultController::contact
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr

boutique:
    path: /{_locale}/boutique
    controller: App\Controller\BoutiqueController::index
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr

rayon:
    path: /{_locale}/boutique/{idCategory}
    controller: App\Controller\BoutiqueController::rayon
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr

panier_index:
    path: /{_locale}/panier
    controller: App\Controller\PanierController::index
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr

panier_ajouter:
    path: /{_locale}/panier/ajouter/{idProduit}/{quantite}
    controller: App\Controller\PanierController::ajouter
    requirements:
        _locale: '%app.supported_locales%'
        quantite: '\d+'
    defaults:
        _locale: fr
        quantite: 1

panier_enlever:
    path: /{_locale}/panier/enlever/{idProduit}/{quantite}
    controller: App\Controller\PanierController::enlever
    requirements:
        _locale: '%app.supported_locales%'
        quantite: '\d+'
    defaults:
        _locale: fr
        quantite: 1

panier_supprimer:
    path: /{_locale}/panier/supprimer/{idProduit}
    controller: App\Controller\PanierController::supprimer
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr

panier_vider:
    path: /{_locale}/panier/vider/
    controller: App\Controller\PanierController::vider
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr